import GObject from 'gi://GObject';
import { SwitchRow } from './ui/activatable-row.js';
import { ShortcutLabel } from './ui/shortcut-label.js';
import { ActionRow, PreferencesRow } from './ui/sensitizable-widgets.js';
import ArchiveList, { ArchiveRow } from './ui/addon-details/archive-list.js';
import AddonDetails from './ui/addon-details.js';
import AddonsPanel, { UsageMeter } from './ui/addons-panel.js';
import AddonsPanelDisk from './ui/addons-panel-disk.js';
import { LaunchpadPage } from './ui/launchpad.js';
import { DownloadPage } from './ui/download-page.js';
import { ProfileBar } from './ui/profile-bar.js';
import InjectButtonSet from './ui/inject-button-set.js';
import { FieldRow } from './ui/field-row.js';
import HeaderBox from './ui/headerbox.js';
import HeaderboxDetachable from './windows/headerbox-detachable.js';
import HeaderboxConsole from './ui/headerbox/console.js';
import HeaderboxBuild from './ui/headerbox/build.js';
import SpinningButton from './ui/spinning-button.js';
import AddAddonUrl, { InputUrl, PreviewDownload } from './dialogs/add-addon-url.js';
import AddAddonName from './dialogs/add-addon-name.js';

GObject.type_ensure(SwitchRow.$gtype);
GObject.type_ensure(ShortcutLabel.$gtype);
GObject.type_ensure(PreferencesRow.$gtype);
GObject.type_ensure(ArchiveRow.$gtype);
GObject.type_ensure(ArchiveList.$gtype);
GObject.type_ensure(AddonDetails.$gtype);
GObject.type_ensure(ActionRow.$gtype);
GObject.type_ensure(UsageMeter.$gtype);
GObject.type_ensure(AddonsPanelDisk.$gtype);
GObject.type_ensure(AddonsPanel.$gtype);
GObject.type_ensure(LaunchpadPage.$gtype);
GObject.type_ensure(DownloadPage.$gtype);
GObject.type_ensure(ProfileBar.$gtype);
GObject.type_ensure(InjectButtonSet.$gtype);
GObject.type_ensure(FieldRow.$gtype);
GObject.type_ensure(HeaderboxDetachable.$gtype);
GObject.type_ensure(HeaderboxConsole.$gtype);
GObject.type_ensure(HeaderboxBuild.$gtype);
GObject.type_ensure(HeaderBox.$gtype);
GObject.type_ensure(SpinningButton.$gtype);
GObject.type_ensure(InputUrl.$gtype);
GObject.type_ensure(PreviewDownload.$gtype);
GObject.type_ensure(AddAddonUrl.$gtype);
GObject.type_ensure(AddAddonName.$gtype);
